/**
 * datalake-cache.appspot.com
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package be.ing.api.chatbot.service.model.datalake;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.LocalDateTime;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * CleanMember
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-24T11:09:35.462+02:00")
public class CleanMember   {
  @SerializedName("active")
  private Boolean active = null;

  @SerializedName("affiliateNumber")
  private String affiliateNumber = null;

  @SerializedName("clubId")
  private String clubId = null;

  @SerializedName("creationDate")
  private LocalDateTime creationDate = null;

  @SerializedName("deltaId")
  private String deltaId = null;

  @SerializedName("deltaObjectId")
  private String deltaObjectId = null;

  @SerializedName("deltaOperation")
  private Operation deltaOperation = null;

  @SerializedName("deltaTimestamp")
  private Long deltaTimestamp = null;

  @SerializedName("deltaTimestampDS")
  private Long deltaTimestampDS = null;

  @SerializedName("deltaType")
  private KbvbEntityType deltaType = null;

  @SerializedName("discipline")
  private String discipline = null;

  @SerializedName("endDateMembership")
  private LocalDateTime endDateMembership = null;

  @SerializedName("entityId")
  private String entityId = null;

  @SerializedName("extraUnknownFields")
  private List<UnknownObject> extraUnknownFields = new ArrayList<UnknownObject>();

  @SerializedName("functions")
  private List<String> functions = new ArrayList<String>();

  @SerializedName("id")
  private String id = null;

  @SerializedName("lastModified")
  private LocalDateTime lastModified = null;

  @SerializedName("links")
  private List<Link> links = new ArrayList<Link>();

  @SerializedName("refereeId")
  private String refereeId = null;

  @SerializedName("refereeObserverId")
  private String refereeObserverId = null;

  @SerializedName("startDateOfRegistration")
  private LocalDateTime startDateOfRegistration = null;

  public CleanMember active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public CleanMember affiliateNumber(String affiliateNumber) {
    this.affiliateNumber = affiliateNumber;
    return this;
  }

   /**
   * Get affiliateNumber
   * @return affiliateNumber
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAffiliateNumber() {
    return affiliateNumber;
  }

  public void setAffiliateNumber(String affiliateNumber) {
    this.affiliateNumber = affiliateNumber;
  }

  public CleanMember clubId(String clubId) {
    this.clubId = clubId;
    return this;
  }

   /**
   * Get clubId
   * @return clubId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getClubId() {
    return clubId;
  }

  public void setClubId(String clubId) {
    this.clubId = clubId;
  }

  public CleanMember creationDate(LocalDateTime creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
   * Get creationDate
   * @return creationDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public LocalDateTime getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(LocalDateTime creationDate) {
    this.creationDate = creationDate;
  }

  public CleanMember deltaId(String deltaId) {
    this.deltaId = deltaId;
    return this;
  }

   /**
   * Get deltaId
   * @return deltaId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDeltaId() {
    return deltaId;
  }

  public void setDeltaId(String deltaId) {
    this.deltaId = deltaId;
  }

  public CleanMember deltaObjectId(String deltaObjectId) {
    this.deltaObjectId = deltaObjectId;
    return this;
  }

   /**
   * Get deltaObjectId
   * @return deltaObjectId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDeltaObjectId() {
    return deltaObjectId;
  }

  public void setDeltaObjectId(String deltaObjectId) {
    this.deltaObjectId = deltaObjectId;
  }

  public CleanMember deltaOperation(Operation deltaOperation) {
    this.deltaOperation = deltaOperation;
    return this;
  }

   /**
   * Get deltaOperation
   * @return deltaOperation
  **/
  @ApiModelProperty(example = "null", value = "")
  public Operation getDeltaOperation() {
    return deltaOperation;
  }

  public void setDeltaOperation(Operation deltaOperation) {
    this.deltaOperation = deltaOperation;
  }

  public CleanMember deltaTimestamp(Long deltaTimestamp) {
    this.deltaTimestamp = deltaTimestamp;
    return this;
  }

   /**
   * Get deltaTimestamp
   * @return deltaTimestamp
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getDeltaTimestamp() {
    return deltaTimestamp;
  }

  public void setDeltaTimestamp(Long deltaTimestamp) {
    this.deltaTimestamp = deltaTimestamp;
  }

  public CleanMember deltaTimestampDS(Long deltaTimestampDS) {
    this.deltaTimestampDS = deltaTimestampDS;
    return this;
  }

   /**
   * Get deltaTimestampDS
   * @return deltaTimestampDS
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getDeltaTimestampDS() {
    return deltaTimestampDS;
  }

  public void setDeltaTimestampDS(Long deltaTimestampDS) {
    this.deltaTimestampDS = deltaTimestampDS;
  }

  public CleanMember deltaType(KbvbEntityType deltaType) {
    this.deltaType = deltaType;
    return this;
  }

   /**
   * Get deltaType
   * @return deltaType
  **/
  @ApiModelProperty(example = "null", value = "")
  public KbvbEntityType getDeltaType() {
    return deltaType;
  }

  public void setDeltaType(KbvbEntityType deltaType) {
    this.deltaType = deltaType;
  }

  public CleanMember discipline(String discipline) {
    this.discipline = discipline;
    return this;
  }

   /**
   * Get discipline
   * @return discipline
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDiscipline() {
    return discipline;
  }

  public void setDiscipline(String discipline) {
    this.discipline = discipline;
  }

  public CleanMember endDateMembership(LocalDateTime endDateMembership) {
    this.endDateMembership = endDateMembership;
    return this;
  }

   /**
   * Get endDateMembership
   * @return endDateMembership
  **/
  @ApiModelProperty(example = "null", value = "")
  public LocalDateTime getEndDateMembership() {
    return endDateMembership;
  }

  public void setEndDateMembership(LocalDateTime endDateMembership) {
    this.endDateMembership = endDateMembership;
  }

  public CleanMember entityId(String entityId) {
    this.entityId = entityId;
    return this;
  }

   /**
   * Get entityId
   * @return entityId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEntityId() {
    return entityId;
  }

  public void setEntityId(String entityId) {
    this.entityId = entityId;
  }

  public CleanMember extraUnknownFields(List<UnknownObject> extraUnknownFields) {
    this.extraUnknownFields = extraUnknownFields;
    return this;
  }

  public CleanMember addExtraUnknownFieldsItem(UnknownObject extraUnknownFieldsItem) {
    this.extraUnknownFields.add(extraUnknownFieldsItem);
    return this;
  }

   /**
   * Get extraUnknownFields
   * @return extraUnknownFields
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<UnknownObject> getExtraUnknownFields() {
    return extraUnknownFields;
  }

  public void setExtraUnknownFields(List<UnknownObject> extraUnknownFields) {
    this.extraUnknownFields = extraUnknownFields;
  }

  public CleanMember functions(List<String> functions) {
    this.functions = functions;
    return this;
  }

  public CleanMember addFunctionsItem(String functionsItem) {
    this.functions.add(functionsItem);
    return this;
  }

   /**
   * Get functions
   * @return functions
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getFunctions() {
    return functions;
  }

  public void setFunctions(List<String> functions) {
    this.functions = functions;
  }

  public CleanMember id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public CleanMember lastModified(LocalDateTime lastModified) {
    this.lastModified = lastModified;
    return this;
  }

   /**
   * Get lastModified
   * @return lastModified
  **/
  @ApiModelProperty(example = "null", value = "")
  public LocalDateTime getLastModified() {
    return lastModified;
  }

  public void setLastModified(LocalDateTime lastModified) {
    this.lastModified = lastModified;
  }

  public CleanMember links(List<Link> links) {
    this.links = links;
    return this;
  }

  public CleanMember addLinksItem(Link linksItem) {
    this.links.add(linksItem);
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Link> getLinks() {
    return links;
  }

  public void setLinks(List<Link> links) {
    this.links = links;
  }

  public CleanMember refereeId(String refereeId) {
    this.refereeId = refereeId;
    return this;
  }

   /**
   * Get refereeId
   * @return refereeId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRefereeId() {
    return refereeId;
  }

  public void setRefereeId(String refereeId) {
    this.refereeId = refereeId;
  }

  public CleanMember refereeObserverId(String refereeObserverId) {
    this.refereeObserverId = refereeObserverId;
    return this;
  }

   /**
   * Get refereeObserverId
   * @return refereeObserverId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRefereeObserverId() {
    return refereeObserverId;
  }

  public void setRefereeObserverId(String refereeObserverId) {
    this.refereeObserverId = refereeObserverId;
  }

  public CleanMember startDateOfRegistration(LocalDateTime startDateOfRegistration) {
    this.startDateOfRegistration = startDateOfRegistration;
    return this;
  }

   /**
   * Get startDateOfRegistration
   * @return startDateOfRegistration
  **/
  @ApiModelProperty(example = "null", value = "")
  public LocalDateTime getStartDateOfRegistration() {
    return startDateOfRegistration;
  }

  public void setStartDateOfRegistration(LocalDateTime startDateOfRegistration) {
    this.startDateOfRegistration = startDateOfRegistration;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CleanMember cleanMember = (CleanMember) o;
    return Objects.equals(this.active, cleanMember.active) &&
        Objects.equals(this.affiliateNumber, cleanMember.affiliateNumber) &&
        Objects.equals(this.clubId, cleanMember.clubId) &&
        Objects.equals(this.creationDate, cleanMember.creationDate) &&
        Objects.equals(this.deltaId, cleanMember.deltaId) &&
        Objects.equals(this.deltaObjectId, cleanMember.deltaObjectId) &&
        Objects.equals(this.deltaOperation, cleanMember.deltaOperation) &&
        Objects.equals(this.deltaTimestamp, cleanMember.deltaTimestamp) &&
        Objects.equals(this.deltaTimestampDS, cleanMember.deltaTimestampDS) &&
        Objects.equals(this.deltaType, cleanMember.deltaType) &&
        Objects.equals(this.discipline, cleanMember.discipline) &&
        Objects.equals(this.endDateMembership, cleanMember.endDateMembership) &&
        Objects.equals(this.entityId, cleanMember.entityId) &&
        Objects.equals(this.extraUnknownFields, cleanMember.extraUnknownFields) &&
        Objects.equals(this.functions, cleanMember.functions) &&
        Objects.equals(this.id, cleanMember.id) &&
        Objects.equals(this.lastModified, cleanMember.lastModified) &&
        Objects.equals(this.links, cleanMember.links) &&
        Objects.equals(this.refereeId, cleanMember.refereeId) &&
        Objects.equals(this.refereeObserverId, cleanMember.refereeObserverId) &&
        Objects.equals(this.startDateOfRegistration, cleanMember.startDateOfRegistration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(active, affiliateNumber, clubId, creationDate, deltaId, deltaObjectId, deltaOperation, deltaTimestamp, deltaTimestampDS, deltaType, discipline, endDateMembership, entityId, extraUnknownFields, functions, id, lastModified, links, refereeId, refereeObserverId, startDateOfRegistration);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CleanMember {\n");
    
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    affiliateNumber: ").append(toIndentedString(affiliateNumber)).append("\n");
    sb.append("    clubId: ").append(toIndentedString(clubId)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    deltaId: ").append(toIndentedString(deltaId)).append("\n");
    sb.append("    deltaObjectId: ").append(toIndentedString(deltaObjectId)).append("\n");
    sb.append("    deltaOperation: ").append(toIndentedString(deltaOperation)).append("\n");
    sb.append("    deltaTimestamp: ").append(toIndentedString(deltaTimestamp)).append("\n");
    sb.append("    deltaTimestampDS: ").append(toIndentedString(deltaTimestampDS)).append("\n");
    sb.append("    deltaType: ").append(toIndentedString(deltaType)).append("\n");
    sb.append("    discipline: ").append(toIndentedString(discipline)).append("\n");
    sb.append("    endDateMembership: ").append(toIndentedString(endDateMembership)).append("\n");
    sb.append("    entityId: ").append(toIndentedString(entityId)).append("\n");
    sb.append("    extraUnknownFields: ").append(toIndentedString(extraUnknownFields)).append("\n");
    sb.append("    functions: ").append(toIndentedString(functions)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lastModified: ").append(toIndentedString(lastModified)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    refereeId: ").append(toIndentedString(refereeId)).append("\n");
    sb.append("    refereeObserverId: ").append(toIndentedString(refereeObserverId)).append("\n");
    sb.append("    startDateOfRegistration: ").append(toIndentedString(startDateOfRegistration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

