/**
 * datalake-cache.appspot.com
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package be.ing.api.chatbot.service.model.datalake;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * CleanDlkFan
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-24T11:09:35.462+02:00")
public class CleanDlkFan   {
  @SerializedName("fanClubId")
  private String fanClubId = null;

  @SerializedName("fanNumber")
  private String fanNumber = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("links")
  private List<Link> links = new ArrayList<Link>();

  @SerializedName("roles")
  private List<String> roles = new ArrayList<String>();

  @SerializedName("status")
  private String status = null;

  @SerializedName("wheelChair")
  private String wheelChair = null;

  public CleanDlkFan fanClubId(String fanClubId) {
    this.fanClubId = fanClubId;
    return this;
  }

   /**
   * Get fanClubId
   * @return fanClubId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFanClubId() {
    return fanClubId;
  }

  public void setFanClubId(String fanClubId) {
    this.fanClubId = fanClubId;
  }

  public CleanDlkFan fanNumber(String fanNumber) {
    this.fanNumber = fanNumber;
    return this;
  }

   /**
   * Get fanNumber
   * @return fanNumber
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFanNumber() {
    return fanNumber;
  }

  public void setFanNumber(String fanNumber) {
    this.fanNumber = fanNumber;
  }

  public CleanDlkFan id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public CleanDlkFan links(List<Link> links) {
    this.links = links;
    return this;
  }

  public CleanDlkFan addLinksItem(Link linksItem) {
    this.links.add(linksItem);
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Link> getLinks() {
    return links;
  }

  public void setLinks(List<Link> links) {
    this.links = links;
  }

  public CleanDlkFan roles(List<String> roles) {
    this.roles = roles;
    return this;
  }

  public CleanDlkFan addRolesItem(String rolesItem) {
    this.roles.add(rolesItem);
    return this;
  }

   /**
   * Get roles
   * @return roles
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getRoles() {
    return roles;
  }

  public void setRoles(List<String> roles) {
    this.roles = roles;
  }

  public CleanDlkFan status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public CleanDlkFan wheelChair(String wheelChair) {
    this.wheelChair = wheelChair;
    return this;
  }

   /**
   * Get wheelChair
   * @return wheelChair
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getWheelChair() {
    return wheelChair;
  }

  public void setWheelChair(String wheelChair) {
    this.wheelChair = wheelChair;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CleanDlkFan cleanDlkFan = (CleanDlkFan) o;
    return Objects.equals(this.fanClubId, cleanDlkFan.fanClubId) &&
        Objects.equals(this.fanNumber, cleanDlkFan.fanNumber) &&
        Objects.equals(this.id, cleanDlkFan.id) &&
        Objects.equals(this.links, cleanDlkFan.links) &&
        Objects.equals(this.roles, cleanDlkFan.roles) &&
        Objects.equals(this.status, cleanDlkFan.status) &&
        Objects.equals(this.wheelChair, cleanDlkFan.wheelChair);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fanClubId, fanNumber, id, links, roles, status, wheelChair);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CleanDlkFan {\n");
    
    sb.append("    fanClubId: ").append(toIndentedString(fanClubId)).append("\n");
    sb.append("    fanNumber: ").append(toIndentedString(fanNumber)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    wheelChair: ").append(toIndentedString(wheelChair)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

