/**
 * datalake-cache.appspot.com
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package be.ing.api.chatbot.service.model.datalake;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.LocalDateTime;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * CleanStaffSelection
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-24T11:09:35.462+02:00")
public class CleanStaffSelection   {
  @SerializedName("active")
  private Boolean active = null;

  @SerializedName("creationDate")
  private LocalDateTime creationDate = null;

  @SerializedName("deltaId")
  private String deltaId = null;

  @SerializedName("deltaObjectId")
  private String deltaObjectId = null;

  @SerializedName("deltaOperation")
  private Operation deltaOperation = null;

  @SerializedName("deltaTimestamp")
  private Long deltaTimestamp = null;

  @SerializedName("deltaTimestampDS")
  private Long deltaTimestampDS = null;

  @SerializedName("deltaType")
  private KbvbEntityType deltaType = null;

  @SerializedName("empty")
  private Boolean empty = null;

  @SerializedName("entityId")
  private String entityId = null;

  @SerializedName("extraUnknownFields")
  private List<UnknownObject> extraUnknownFields = new ArrayList<UnknownObject>();

  @SerializedName("id")
  private String id = null;

  @SerializedName("labelFunctionDe")
  private String labelFunctionDe = null;

  @SerializedName("labelFunctionEn")
  private String labelFunctionEn = null;

  @SerializedName("labelFunctionFr")
  private String labelFunctionFr = null;

  @SerializedName("labelFunctionNl")
  private String labelFunctionNl = null;

  @SerializedName("lastModified")
  private LocalDateTime lastModified = null;

  @SerializedName("links")
  private List<Link> links = new ArrayList<Link>();

  @SerializedName("matchId")
  private String matchId = null;

  @SerializedName("memberId")
  private String memberId = null;

  @SerializedName("minuteRed")
  private Integer minuteRed = null;

  @SerializedName("teamId")
  private String teamId = null;

  public CleanStaffSelection active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public CleanStaffSelection creationDate(LocalDateTime creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
   * Get creationDate
   * @return creationDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public LocalDateTime getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(LocalDateTime creationDate) {
    this.creationDate = creationDate;
  }

  public CleanStaffSelection deltaId(String deltaId) {
    this.deltaId = deltaId;
    return this;
  }

   /**
   * Get deltaId
   * @return deltaId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDeltaId() {
    return deltaId;
  }

  public void setDeltaId(String deltaId) {
    this.deltaId = deltaId;
  }

  public CleanStaffSelection deltaObjectId(String deltaObjectId) {
    this.deltaObjectId = deltaObjectId;
    return this;
  }

   /**
   * Get deltaObjectId
   * @return deltaObjectId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDeltaObjectId() {
    return deltaObjectId;
  }

  public void setDeltaObjectId(String deltaObjectId) {
    this.deltaObjectId = deltaObjectId;
  }

  public CleanStaffSelection deltaOperation(Operation deltaOperation) {
    this.deltaOperation = deltaOperation;
    return this;
  }

   /**
   * Get deltaOperation
   * @return deltaOperation
  **/
  @ApiModelProperty(example = "null", value = "")
  public Operation getDeltaOperation() {
    return deltaOperation;
  }

  public void setDeltaOperation(Operation deltaOperation) {
    this.deltaOperation = deltaOperation;
  }

  public CleanStaffSelection deltaTimestamp(Long deltaTimestamp) {
    this.deltaTimestamp = deltaTimestamp;
    return this;
  }

   /**
   * Get deltaTimestamp
   * @return deltaTimestamp
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getDeltaTimestamp() {
    return deltaTimestamp;
  }

  public void setDeltaTimestamp(Long deltaTimestamp) {
    this.deltaTimestamp = deltaTimestamp;
  }

  public CleanStaffSelection deltaTimestampDS(Long deltaTimestampDS) {
    this.deltaTimestampDS = deltaTimestampDS;
    return this;
  }

   /**
   * Get deltaTimestampDS
   * @return deltaTimestampDS
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getDeltaTimestampDS() {
    return deltaTimestampDS;
  }

  public void setDeltaTimestampDS(Long deltaTimestampDS) {
    this.deltaTimestampDS = deltaTimestampDS;
  }

  public CleanStaffSelection deltaType(KbvbEntityType deltaType) {
    this.deltaType = deltaType;
    return this;
  }

   /**
   * Get deltaType
   * @return deltaType
  **/
  @ApiModelProperty(example = "null", value = "")
  public KbvbEntityType getDeltaType() {
    return deltaType;
  }

  public void setDeltaType(KbvbEntityType deltaType) {
    this.deltaType = deltaType;
  }

  public CleanStaffSelection empty(Boolean empty) {
    this.empty = empty;
    return this;
  }

   /**
   * Get empty
   * @return empty
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getEmpty() {
    return empty;
  }

  public void setEmpty(Boolean empty) {
    this.empty = empty;
  }

  public CleanStaffSelection entityId(String entityId) {
    this.entityId = entityId;
    return this;
  }

   /**
   * Get entityId
   * @return entityId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEntityId() {
    return entityId;
  }

  public void setEntityId(String entityId) {
    this.entityId = entityId;
  }

  public CleanStaffSelection extraUnknownFields(List<UnknownObject> extraUnknownFields) {
    this.extraUnknownFields = extraUnknownFields;
    return this;
  }

  public CleanStaffSelection addExtraUnknownFieldsItem(UnknownObject extraUnknownFieldsItem) {
    this.extraUnknownFields.add(extraUnknownFieldsItem);
    return this;
  }

   /**
   * Get extraUnknownFields
   * @return extraUnknownFields
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<UnknownObject> getExtraUnknownFields() {
    return extraUnknownFields;
  }

  public void setExtraUnknownFields(List<UnknownObject> extraUnknownFields) {
    this.extraUnknownFields = extraUnknownFields;
  }

  public CleanStaffSelection id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public CleanStaffSelection labelFunctionDe(String labelFunctionDe) {
    this.labelFunctionDe = labelFunctionDe;
    return this;
  }

   /**
   * Get labelFunctionDe
   * @return labelFunctionDe
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLabelFunctionDe() {
    return labelFunctionDe;
  }

  public void setLabelFunctionDe(String labelFunctionDe) {
    this.labelFunctionDe = labelFunctionDe;
  }

  public CleanStaffSelection labelFunctionEn(String labelFunctionEn) {
    this.labelFunctionEn = labelFunctionEn;
    return this;
  }

   /**
   * Get labelFunctionEn
   * @return labelFunctionEn
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLabelFunctionEn() {
    return labelFunctionEn;
  }

  public void setLabelFunctionEn(String labelFunctionEn) {
    this.labelFunctionEn = labelFunctionEn;
  }

  public CleanStaffSelection labelFunctionFr(String labelFunctionFr) {
    this.labelFunctionFr = labelFunctionFr;
    return this;
  }

   /**
   * Get labelFunctionFr
   * @return labelFunctionFr
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLabelFunctionFr() {
    return labelFunctionFr;
  }

  public void setLabelFunctionFr(String labelFunctionFr) {
    this.labelFunctionFr = labelFunctionFr;
  }

  public CleanStaffSelection labelFunctionNl(String labelFunctionNl) {
    this.labelFunctionNl = labelFunctionNl;
    return this;
  }

   /**
   * Get labelFunctionNl
   * @return labelFunctionNl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLabelFunctionNl() {
    return labelFunctionNl;
  }

  public void setLabelFunctionNl(String labelFunctionNl) {
    this.labelFunctionNl = labelFunctionNl;
  }

  public CleanStaffSelection lastModified(LocalDateTime lastModified) {
    this.lastModified = lastModified;
    return this;
  }

   /**
   * Get lastModified
   * @return lastModified
  **/
  @ApiModelProperty(example = "null", value = "")
  public LocalDateTime getLastModified() {
    return lastModified;
  }

  public void setLastModified(LocalDateTime lastModified) {
    this.lastModified = lastModified;
  }

  public CleanStaffSelection links(List<Link> links) {
    this.links = links;
    return this;
  }

  public CleanStaffSelection addLinksItem(Link linksItem) {
    this.links.add(linksItem);
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Link> getLinks() {
    return links;
  }

  public void setLinks(List<Link> links) {
    this.links = links;
  }

  public CleanStaffSelection matchId(String matchId) {
    this.matchId = matchId;
    return this;
  }

   /**
   * Get matchId
   * @return matchId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMatchId() {
    return matchId;
  }

  public void setMatchId(String matchId) {
    this.matchId = matchId;
  }

  public CleanStaffSelection memberId(String memberId) {
    this.memberId = memberId;
    return this;
  }

   /**
   * Get memberId
   * @return memberId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMemberId() {
    return memberId;
  }

  public void setMemberId(String memberId) {
    this.memberId = memberId;
  }

  public CleanStaffSelection minuteRed(Integer minuteRed) {
    this.minuteRed = minuteRed;
    return this;
  }

   /**
   * Get minuteRed
   * @return minuteRed
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getMinuteRed() {
    return minuteRed;
  }

  public void setMinuteRed(Integer minuteRed) {
    this.minuteRed = minuteRed;
  }

  public CleanStaffSelection teamId(String teamId) {
    this.teamId = teamId;
    return this;
  }

   /**
   * Get teamId
   * @return teamId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTeamId() {
    return teamId;
  }

  public void setTeamId(String teamId) {
    this.teamId = teamId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CleanStaffSelection cleanStaffSelection = (CleanStaffSelection) o;
    return Objects.equals(this.active, cleanStaffSelection.active) &&
        Objects.equals(this.creationDate, cleanStaffSelection.creationDate) &&
        Objects.equals(this.deltaId, cleanStaffSelection.deltaId) &&
        Objects.equals(this.deltaObjectId, cleanStaffSelection.deltaObjectId) &&
        Objects.equals(this.deltaOperation, cleanStaffSelection.deltaOperation) &&
        Objects.equals(this.deltaTimestamp, cleanStaffSelection.deltaTimestamp) &&
        Objects.equals(this.deltaTimestampDS, cleanStaffSelection.deltaTimestampDS) &&
        Objects.equals(this.deltaType, cleanStaffSelection.deltaType) &&
        Objects.equals(this.empty, cleanStaffSelection.empty) &&
        Objects.equals(this.entityId, cleanStaffSelection.entityId) &&
        Objects.equals(this.extraUnknownFields, cleanStaffSelection.extraUnknownFields) &&
        Objects.equals(this.id, cleanStaffSelection.id) &&
        Objects.equals(this.labelFunctionDe, cleanStaffSelection.labelFunctionDe) &&
        Objects.equals(this.labelFunctionEn, cleanStaffSelection.labelFunctionEn) &&
        Objects.equals(this.labelFunctionFr, cleanStaffSelection.labelFunctionFr) &&
        Objects.equals(this.labelFunctionNl, cleanStaffSelection.labelFunctionNl) &&
        Objects.equals(this.lastModified, cleanStaffSelection.lastModified) &&
        Objects.equals(this.links, cleanStaffSelection.links) &&
        Objects.equals(this.matchId, cleanStaffSelection.matchId) &&
        Objects.equals(this.memberId, cleanStaffSelection.memberId) &&
        Objects.equals(this.minuteRed, cleanStaffSelection.minuteRed) &&
        Objects.equals(this.teamId, cleanStaffSelection.teamId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(active, creationDate, deltaId, deltaObjectId, deltaOperation, deltaTimestamp, deltaTimestampDS, deltaType, empty, entityId, extraUnknownFields, id, labelFunctionDe, labelFunctionEn, labelFunctionFr, labelFunctionNl, lastModified, links, matchId, memberId, minuteRed, teamId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CleanStaffSelection {\n");
    
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    deltaId: ").append(toIndentedString(deltaId)).append("\n");
    sb.append("    deltaObjectId: ").append(toIndentedString(deltaObjectId)).append("\n");
    sb.append("    deltaOperation: ").append(toIndentedString(deltaOperation)).append("\n");
    sb.append("    deltaTimestamp: ").append(toIndentedString(deltaTimestamp)).append("\n");
    sb.append("    deltaTimestampDS: ").append(toIndentedString(deltaTimestampDS)).append("\n");
    sb.append("    deltaType: ").append(toIndentedString(deltaType)).append("\n");
    sb.append("    empty: ").append(toIndentedString(empty)).append("\n");
    sb.append("    entityId: ").append(toIndentedString(entityId)).append("\n");
    sb.append("    extraUnknownFields: ").append(toIndentedString(extraUnknownFields)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    labelFunctionDe: ").append(toIndentedString(labelFunctionDe)).append("\n");
    sb.append("    labelFunctionEn: ").append(toIndentedString(labelFunctionEn)).append("\n");
    sb.append("    labelFunctionFr: ").append(toIndentedString(labelFunctionFr)).append("\n");
    sb.append("    labelFunctionNl: ").append(toIndentedString(labelFunctionNl)).append("\n");
    sb.append("    lastModified: ").append(toIndentedString(lastModified)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    matchId: ").append(toIndentedString(matchId)).append("\n");
    sb.append("    memberId: ").append(toIndentedString(memberId)).append("\n");
    sb.append("    minuteRed: ").append(toIndentedString(minuteRed)).append("\n");
    sb.append("    teamId: ").append(toIndentedString(teamId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

