/**
 * datalake-cache.appspot.com
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package be.ing.api.chatbot.service.model.datalake;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;


/**
 * CleanDLKFanProductMatchesProduct
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-24T11:09:35.462+02:00")
public class CleanDLKFanProductMatchesProduct   {
  @SerializedName("awayTeam")
  private String awayTeam = null;

  @SerializedName("cateId")
  private Long cateId = null;

  @SerializedName("groundName")
  private String groundName = null;

  @SerializedName("homeTeam")
  private String homeTeam = null;

  @SerializedName("startDate")
  private String startDate = null;

  @SerializedName("typeMatch")
  private Long typeMatch = null;

  public CleanDLKFanProductMatchesProduct awayTeam(String awayTeam) {
    this.awayTeam = awayTeam;
    return this;
  }

   /**
   * Get awayTeam
   * @return awayTeam
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAwayTeam() {
    return awayTeam;
  }

  public void setAwayTeam(String awayTeam) {
    this.awayTeam = awayTeam;
  }

  public CleanDLKFanProductMatchesProduct cateId(Long cateId) {
    this.cateId = cateId;
    return this;
  }

   /**
   * Get cateId
   * @return cateId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getCateId() {
    return cateId;
  }

  public void setCateId(Long cateId) {
    this.cateId = cateId;
  }

  public CleanDLKFanProductMatchesProduct groundName(String groundName) {
    this.groundName = groundName;
    return this;
  }

   /**
   * Get groundName
   * @return groundName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGroundName() {
    return groundName;
  }

  public void setGroundName(String groundName) {
    this.groundName = groundName;
  }

  public CleanDLKFanProductMatchesProduct homeTeam(String homeTeam) {
    this.homeTeam = homeTeam;
    return this;
  }

   /**
   * Get homeTeam
   * @return homeTeam
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getHomeTeam() {
    return homeTeam;
  }

  public void setHomeTeam(String homeTeam) {
    this.homeTeam = homeTeam;
  }

  public CleanDLKFanProductMatchesProduct startDate(String startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStartDate() {
    return startDate;
  }

  public void setStartDate(String startDate) {
    this.startDate = startDate;
  }

  public CleanDLKFanProductMatchesProduct typeMatch(Long typeMatch) {
    this.typeMatch = typeMatch;
    return this;
  }

   /**
   * Get typeMatch
   * @return typeMatch
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getTypeMatch() {
    return typeMatch;
  }

  public void setTypeMatch(Long typeMatch) {
    this.typeMatch = typeMatch;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CleanDLKFanProductMatchesProduct cleanDLKFanProductMatchesProduct = (CleanDLKFanProductMatchesProduct) o;
    return Objects.equals(this.awayTeam, cleanDLKFanProductMatchesProduct.awayTeam) &&
        Objects.equals(this.cateId, cleanDLKFanProductMatchesProduct.cateId) &&
        Objects.equals(this.groundName, cleanDLKFanProductMatchesProduct.groundName) &&
        Objects.equals(this.homeTeam, cleanDLKFanProductMatchesProduct.homeTeam) &&
        Objects.equals(this.startDate, cleanDLKFanProductMatchesProduct.startDate) &&
        Objects.equals(this.typeMatch, cleanDLKFanProductMatchesProduct.typeMatch);
  }

  @Override
  public int hashCode() {
    return Objects.hash(awayTeam, cateId, groundName, homeTeam, startDate, typeMatch);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CleanDLKFanProductMatchesProduct {\n");
    
    sb.append("    awayTeam: ").append(toIndentedString(awayTeam)).append("\n");
    sb.append("    cateId: ").append(toIndentedString(cateId)).append("\n");
    sb.append("    groundName: ").append(toIndentedString(groundName)).append("\n");
    sb.append("    homeTeam: ").append(toIndentedString(homeTeam)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    typeMatch: ").append(toIndentedString(typeMatch)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

