/**
 * datalake-cache.appspot.com
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package be.ing.api.chatbot.service.model.datalake;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.LocalDateTime;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * CleanInternationalsMatches
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-24T11:09:35.462+02:00")
public class CleanInternationalsMatches   {
  @SerializedName("active")
  private Boolean active = null;

  @SerializedName("awayTeam")
  private CleanInternationalsMatchesMatchTeam awayTeam = null;

  @SerializedName("category")
  private String category = null;

  @SerializedName("categoryTeamId")
  private String categoryTeamId = null;

  @SerializedName("city")
  private String city = null;

  @SerializedName("cityId")
  private Long cityId = null;

  @SerializedName("clubCountry")
  private String clubCountry = null;

  @SerializedName("clubName")
  private String clubName = null;

  @SerializedName("clubNameId")
  private Long clubNameId = null;

  @SerializedName("countryId")
  private Long countryId = null;

  @SerializedName("creationDate")
  private LocalDateTime creationDate = null;

  @SerializedName("deltaId")
  private String deltaId = null;

  @SerializedName("deltaObjectId")
  private String deltaObjectId = null;

  @SerializedName("deltaOperation")
  private Operation deltaOperation = null;

  @SerializedName("deltaTimestamp")
  private Long deltaTimestamp = null;

  @SerializedName("deltaTimestampDS")
  private Long deltaTimestampDS = null;

  @SerializedName("deltaType")
  private KbvbEntityType deltaType = null;

  @SerializedName("discipline")
  private String discipline = null;

  @SerializedName("endDateAndTime")
  private String endDateAndTime = null;

  @SerializedName("entityId")
  private String entityId = null;

  @SerializedName("extraUnknownFields")
  private List<UnknownObject> extraUnknownFields = new ArrayList<UnknownObject>();

  @SerializedName("finals")
  private String finals = null;

  @SerializedName("finalsId")
  private Long finalsId = null;

  @SerializedName("gameType")
  private String gameType = null;

  @SerializedName("gameTypeDetail")
  private String gameTypeDetail = null;

  @SerializedName("groupNumber")
  private String groupNumber = null;

  @SerializedName("homeTeam")
  private CleanInternationalsMatchesMatchTeam homeTeam = null;

  @SerializedName("hostCountry")
  private String hostCountry = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("lastModified")
  private LocalDateTime lastModified = null;

  @SerializedName("links")
  private List<Link> links = new ArrayList<Link>();

  @SerializedName("officialGameNumber")
  private Long officialGameNumber = null;

  @SerializedName("sequenceNumber")
  private Long sequenceNumber = null;

  @SerializedName("stadium")
  private String stadium = null;

  @SerializedName("stadiumId")
  private Long stadiumId = null;

  @SerializedName("startDateAndTime")
  private String startDateAndTime = null;

  @SerializedName("status")
  private String status = null;

  public CleanInternationalsMatches active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public CleanInternationalsMatches awayTeam(CleanInternationalsMatchesMatchTeam awayTeam) {
    this.awayTeam = awayTeam;
    return this;
  }

   /**
   * Get awayTeam
   * @return awayTeam
  **/
  @ApiModelProperty(example = "null", value = "")
  public CleanInternationalsMatchesMatchTeam getAwayTeam() {
    return awayTeam;
  }

  public void setAwayTeam(CleanInternationalsMatchesMatchTeam awayTeam) {
    this.awayTeam = awayTeam;
  }

  public CleanInternationalsMatches category(String category) {
    this.category = category;
    return this;
  }

   /**
   * Get category
   * @return category
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCategory() {
    return category;
  }

  public void setCategory(String category) {
    this.category = category;
  }

  public CleanInternationalsMatches categoryTeamId(String categoryTeamId) {
    this.categoryTeamId = categoryTeamId;
    return this;
  }

   /**
   * Get categoryTeamId
   * @return categoryTeamId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCategoryTeamId() {
    return categoryTeamId;
  }

  public void setCategoryTeamId(String categoryTeamId) {
    this.categoryTeamId = categoryTeamId;
  }

  public CleanInternationalsMatches city(String city) {
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public CleanInternationalsMatches cityId(Long cityId) {
    this.cityId = cityId;
    return this;
  }

   /**
   * Get cityId
   * @return cityId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getCityId() {
    return cityId;
  }

  public void setCityId(Long cityId) {
    this.cityId = cityId;
  }

  public CleanInternationalsMatches clubCountry(String clubCountry) {
    this.clubCountry = clubCountry;
    return this;
  }

   /**
   * Get clubCountry
   * @return clubCountry
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getClubCountry() {
    return clubCountry;
  }

  public void setClubCountry(String clubCountry) {
    this.clubCountry = clubCountry;
  }

  public CleanInternationalsMatches clubName(String clubName) {
    this.clubName = clubName;
    return this;
  }

   /**
   * Get clubName
   * @return clubName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getClubName() {
    return clubName;
  }

  public void setClubName(String clubName) {
    this.clubName = clubName;
  }

  public CleanInternationalsMatches clubNameId(Long clubNameId) {
    this.clubNameId = clubNameId;
    return this;
  }

   /**
   * Get clubNameId
   * @return clubNameId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getClubNameId() {
    return clubNameId;
  }

  public void setClubNameId(Long clubNameId) {
    this.clubNameId = clubNameId;
  }

  public CleanInternationalsMatches countryId(Long countryId) {
    this.countryId = countryId;
    return this;
  }

   /**
   * Get countryId
   * @return countryId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getCountryId() {
    return countryId;
  }

  public void setCountryId(Long countryId) {
    this.countryId = countryId;
  }

  public CleanInternationalsMatches creationDate(LocalDateTime creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
   * Get creationDate
   * @return creationDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public LocalDateTime getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(LocalDateTime creationDate) {
    this.creationDate = creationDate;
  }

  public CleanInternationalsMatches deltaId(String deltaId) {
    this.deltaId = deltaId;
    return this;
  }

   /**
   * Get deltaId
   * @return deltaId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDeltaId() {
    return deltaId;
  }

  public void setDeltaId(String deltaId) {
    this.deltaId = deltaId;
  }

  public CleanInternationalsMatches deltaObjectId(String deltaObjectId) {
    this.deltaObjectId = deltaObjectId;
    return this;
  }

   /**
   * Get deltaObjectId
   * @return deltaObjectId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDeltaObjectId() {
    return deltaObjectId;
  }

  public void setDeltaObjectId(String deltaObjectId) {
    this.deltaObjectId = deltaObjectId;
  }

  public CleanInternationalsMatches deltaOperation(Operation deltaOperation) {
    this.deltaOperation = deltaOperation;
    return this;
  }

   /**
   * Get deltaOperation
   * @return deltaOperation
  **/
  @ApiModelProperty(example = "null", value = "")
  public Operation getDeltaOperation() {
    return deltaOperation;
  }

  public void setDeltaOperation(Operation deltaOperation) {
    this.deltaOperation = deltaOperation;
  }

  public CleanInternationalsMatches deltaTimestamp(Long deltaTimestamp) {
    this.deltaTimestamp = deltaTimestamp;
    return this;
  }

   /**
   * Get deltaTimestamp
   * @return deltaTimestamp
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getDeltaTimestamp() {
    return deltaTimestamp;
  }

  public void setDeltaTimestamp(Long deltaTimestamp) {
    this.deltaTimestamp = deltaTimestamp;
  }

  public CleanInternationalsMatches deltaTimestampDS(Long deltaTimestampDS) {
    this.deltaTimestampDS = deltaTimestampDS;
    return this;
  }

   /**
   * Get deltaTimestampDS
   * @return deltaTimestampDS
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getDeltaTimestampDS() {
    return deltaTimestampDS;
  }

  public void setDeltaTimestampDS(Long deltaTimestampDS) {
    this.deltaTimestampDS = deltaTimestampDS;
  }

  public CleanInternationalsMatches deltaType(KbvbEntityType deltaType) {
    this.deltaType = deltaType;
    return this;
  }

   /**
   * Get deltaType
   * @return deltaType
  **/
  @ApiModelProperty(example = "null", value = "")
  public KbvbEntityType getDeltaType() {
    return deltaType;
  }

  public void setDeltaType(KbvbEntityType deltaType) {
    this.deltaType = deltaType;
  }

  public CleanInternationalsMatches discipline(String discipline) {
    this.discipline = discipline;
    return this;
  }

   /**
   * Get discipline
   * @return discipline
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDiscipline() {
    return discipline;
  }

  public void setDiscipline(String discipline) {
    this.discipline = discipline;
  }

  public CleanInternationalsMatches endDateAndTime(String endDateAndTime) {
    this.endDateAndTime = endDateAndTime;
    return this;
  }

   /**
   * Get endDateAndTime
   * @return endDateAndTime
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEndDateAndTime() {
    return endDateAndTime;
  }

  public void setEndDateAndTime(String endDateAndTime) {
    this.endDateAndTime = endDateAndTime;
  }

  public CleanInternationalsMatches entityId(String entityId) {
    this.entityId = entityId;
    return this;
  }

   /**
   * Get entityId
   * @return entityId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEntityId() {
    return entityId;
  }

  public void setEntityId(String entityId) {
    this.entityId = entityId;
  }

  public CleanInternationalsMatches extraUnknownFields(List<UnknownObject> extraUnknownFields) {
    this.extraUnknownFields = extraUnknownFields;
    return this;
  }

  public CleanInternationalsMatches addExtraUnknownFieldsItem(UnknownObject extraUnknownFieldsItem) {
    this.extraUnknownFields.add(extraUnknownFieldsItem);
    return this;
  }

   /**
   * Get extraUnknownFields
   * @return extraUnknownFields
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<UnknownObject> getExtraUnknownFields() {
    return extraUnknownFields;
  }

  public void setExtraUnknownFields(List<UnknownObject> extraUnknownFields) {
    this.extraUnknownFields = extraUnknownFields;
  }

  public CleanInternationalsMatches finals(String finals) {
    this.finals = finals;
    return this;
  }

   /**
   * Get finals
   * @return finals
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFinals() {
    return finals;
  }

  public void setFinals(String finals) {
    this.finals = finals;
  }

  public CleanInternationalsMatches finalsId(Long finalsId) {
    this.finalsId = finalsId;
    return this;
  }

   /**
   * Get finalsId
   * @return finalsId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getFinalsId() {
    return finalsId;
  }

  public void setFinalsId(Long finalsId) {
    this.finalsId = finalsId;
  }

  public CleanInternationalsMatches gameType(String gameType) {
    this.gameType = gameType;
    return this;
  }

   /**
   * Get gameType
   * @return gameType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGameType() {
    return gameType;
  }

  public void setGameType(String gameType) {
    this.gameType = gameType;
  }

  public CleanInternationalsMatches gameTypeDetail(String gameTypeDetail) {
    this.gameTypeDetail = gameTypeDetail;
    return this;
  }

   /**
   * Get gameTypeDetail
   * @return gameTypeDetail
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGameTypeDetail() {
    return gameTypeDetail;
  }

  public void setGameTypeDetail(String gameTypeDetail) {
    this.gameTypeDetail = gameTypeDetail;
  }

  public CleanInternationalsMatches groupNumber(String groupNumber) {
    this.groupNumber = groupNumber;
    return this;
  }

   /**
   * Get groupNumber
   * @return groupNumber
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGroupNumber() {
    return groupNumber;
  }

  public void setGroupNumber(String groupNumber) {
    this.groupNumber = groupNumber;
  }

  public CleanInternationalsMatches homeTeam(CleanInternationalsMatchesMatchTeam homeTeam) {
    this.homeTeam = homeTeam;
    return this;
  }

   /**
   * Get homeTeam
   * @return homeTeam
  **/
  @ApiModelProperty(example = "null", value = "")
  public CleanInternationalsMatchesMatchTeam getHomeTeam() {
    return homeTeam;
  }

  public void setHomeTeam(CleanInternationalsMatchesMatchTeam homeTeam) {
    this.homeTeam = homeTeam;
  }

  public CleanInternationalsMatches hostCountry(String hostCountry) {
    this.hostCountry = hostCountry;
    return this;
  }

   /**
   * Get hostCountry
   * @return hostCountry
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getHostCountry() {
    return hostCountry;
  }

  public void setHostCountry(String hostCountry) {
    this.hostCountry = hostCountry;
  }

  public CleanInternationalsMatches id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public CleanInternationalsMatches lastModified(LocalDateTime lastModified) {
    this.lastModified = lastModified;
    return this;
  }

   /**
   * Get lastModified
   * @return lastModified
  **/
  @ApiModelProperty(example = "null", value = "")
  public LocalDateTime getLastModified() {
    return lastModified;
  }

  public void setLastModified(LocalDateTime lastModified) {
    this.lastModified = lastModified;
  }

  public CleanInternationalsMatches links(List<Link> links) {
    this.links = links;
    return this;
  }

  public CleanInternationalsMatches addLinksItem(Link linksItem) {
    this.links.add(linksItem);
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Link> getLinks() {
    return links;
  }

  public void setLinks(List<Link> links) {
    this.links = links;
  }

  public CleanInternationalsMatches officialGameNumber(Long officialGameNumber) {
    this.officialGameNumber = officialGameNumber;
    return this;
  }

   /**
   * Get officialGameNumber
   * @return officialGameNumber
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getOfficialGameNumber() {
    return officialGameNumber;
  }

  public void setOfficialGameNumber(Long officialGameNumber) {
    this.officialGameNumber = officialGameNumber;
  }

  public CleanInternationalsMatches sequenceNumber(Long sequenceNumber) {
    this.sequenceNumber = sequenceNumber;
    return this;
  }

   /**
   * Get sequenceNumber
   * @return sequenceNumber
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getSequenceNumber() {
    return sequenceNumber;
  }

  public void setSequenceNumber(Long sequenceNumber) {
    this.sequenceNumber = sequenceNumber;
  }

  public CleanInternationalsMatches stadium(String stadium) {
    this.stadium = stadium;
    return this;
  }

   /**
   * Get stadium
   * @return stadium
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStadium() {
    return stadium;
  }

  public void setStadium(String stadium) {
    this.stadium = stadium;
  }

  public CleanInternationalsMatches stadiumId(Long stadiumId) {
    this.stadiumId = stadiumId;
    return this;
  }

   /**
   * Get stadiumId
   * @return stadiumId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getStadiumId() {
    return stadiumId;
  }

  public void setStadiumId(Long stadiumId) {
    this.stadiumId = stadiumId;
  }

  public CleanInternationalsMatches startDateAndTime(String startDateAndTime) {
    this.startDateAndTime = startDateAndTime;
    return this;
  }

   /**
   * Get startDateAndTime
   * @return startDateAndTime
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStartDateAndTime() {
    return startDateAndTime;
  }

  public void setStartDateAndTime(String startDateAndTime) {
    this.startDateAndTime = startDateAndTime;
  }

  public CleanInternationalsMatches status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CleanInternationalsMatches cleanInternationalsMatches = (CleanInternationalsMatches) o;
    return Objects.equals(this.active, cleanInternationalsMatches.active) &&
        Objects.equals(this.awayTeam, cleanInternationalsMatches.awayTeam) &&
        Objects.equals(this.category, cleanInternationalsMatches.category) &&
        Objects.equals(this.categoryTeamId, cleanInternationalsMatches.categoryTeamId) &&
        Objects.equals(this.city, cleanInternationalsMatches.city) &&
        Objects.equals(this.cityId, cleanInternationalsMatches.cityId) &&
        Objects.equals(this.clubCountry, cleanInternationalsMatches.clubCountry) &&
        Objects.equals(this.clubName, cleanInternationalsMatches.clubName) &&
        Objects.equals(this.clubNameId, cleanInternationalsMatches.clubNameId) &&
        Objects.equals(this.countryId, cleanInternationalsMatches.countryId) &&
        Objects.equals(this.creationDate, cleanInternationalsMatches.creationDate) &&
        Objects.equals(this.deltaId, cleanInternationalsMatches.deltaId) &&
        Objects.equals(this.deltaObjectId, cleanInternationalsMatches.deltaObjectId) &&
        Objects.equals(this.deltaOperation, cleanInternationalsMatches.deltaOperation) &&
        Objects.equals(this.deltaTimestamp, cleanInternationalsMatches.deltaTimestamp) &&
        Objects.equals(this.deltaTimestampDS, cleanInternationalsMatches.deltaTimestampDS) &&
        Objects.equals(this.deltaType, cleanInternationalsMatches.deltaType) &&
        Objects.equals(this.discipline, cleanInternationalsMatches.discipline) &&
        Objects.equals(this.endDateAndTime, cleanInternationalsMatches.endDateAndTime) &&
        Objects.equals(this.entityId, cleanInternationalsMatches.entityId) &&
        Objects.equals(this.extraUnknownFields, cleanInternationalsMatches.extraUnknownFields) &&
        Objects.equals(this.finals, cleanInternationalsMatches.finals) &&
        Objects.equals(this.finalsId, cleanInternationalsMatches.finalsId) &&
        Objects.equals(this.gameType, cleanInternationalsMatches.gameType) &&
        Objects.equals(this.gameTypeDetail, cleanInternationalsMatches.gameTypeDetail) &&
        Objects.equals(this.groupNumber, cleanInternationalsMatches.groupNumber) &&
        Objects.equals(this.homeTeam, cleanInternationalsMatches.homeTeam) &&
        Objects.equals(this.hostCountry, cleanInternationalsMatches.hostCountry) &&
        Objects.equals(this.id, cleanInternationalsMatches.id) &&
        Objects.equals(this.lastModified, cleanInternationalsMatches.lastModified) &&
        Objects.equals(this.links, cleanInternationalsMatches.links) &&
        Objects.equals(this.officialGameNumber, cleanInternationalsMatches.officialGameNumber) &&
        Objects.equals(this.sequenceNumber, cleanInternationalsMatches.sequenceNumber) &&
        Objects.equals(this.stadium, cleanInternationalsMatches.stadium) &&
        Objects.equals(this.stadiumId, cleanInternationalsMatches.stadiumId) &&
        Objects.equals(this.startDateAndTime, cleanInternationalsMatches.startDateAndTime) &&
        Objects.equals(this.status, cleanInternationalsMatches.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(active, awayTeam, category, categoryTeamId, city, cityId, clubCountry, clubName, clubNameId, countryId, creationDate, deltaId, deltaObjectId, deltaOperation, deltaTimestamp, deltaTimestampDS, deltaType, discipline, endDateAndTime, entityId, extraUnknownFields, finals, finalsId, gameType, gameTypeDetail, groupNumber, homeTeam, hostCountry, id, lastModified, links, officialGameNumber, sequenceNumber, stadium, stadiumId, startDateAndTime, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CleanInternationalsMatches {\n");
    
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    awayTeam: ").append(toIndentedString(awayTeam)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    categoryTeamId: ").append(toIndentedString(categoryTeamId)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    cityId: ").append(toIndentedString(cityId)).append("\n");
    sb.append("    clubCountry: ").append(toIndentedString(clubCountry)).append("\n");
    sb.append("    clubName: ").append(toIndentedString(clubName)).append("\n");
    sb.append("    clubNameId: ").append(toIndentedString(clubNameId)).append("\n");
    sb.append("    countryId: ").append(toIndentedString(countryId)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    deltaId: ").append(toIndentedString(deltaId)).append("\n");
    sb.append("    deltaObjectId: ").append(toIndentedString(deltaObjectId)).append("\n");
    sb.append("    deltaOperation: ").append(toIndentedString(deltaOperation)).append("\n");
    sb.append("    deltaTimestamp: ").append(toIndentedString(deltaTimestamp)).append("\n");
    sb.append("    deltaTimestampDS: ").append(toIndentedString(deltaTimestampDS)).append("\n");
    sb.append("    deltaType: ").append(toIndentedString(deltaType)).append("\n");
    sb.append("    discipline: ").append(toIndentedString(discipline)).append("\n");
    sb.append("    endDateAndTime: ").append(toIndentedString(endDateAndTime)).append("\n");
    sb.append("    entityId: ").append(toIndentedString(entityId)).append("\n");
    sb.append("    extraUnknownFields: ").append(toIndentedString(extraUnknownFields)).append("\n");
    sb.append("    finals: ").append(toIndentedString(finals)).append("\n");
    sb.append("    finalsId: ").append(toIndentedString(finalsId)).append("\n");
    sb.append("    gameType: ").append(toIndentedString(gameType)).append("\n");
    sb.append("    gameTypeDetail: ").append(toIndentedString(gameTypeDetail)).append("\n");
    sb.append("    groupNumber: ").append(toIndentedString(groupNumber)).append("\n");
    sb.append("    homeTeam: ").append(toIndentedString(homeTeam)).append("\n");
    sb.append("    hostCountry: ").append(toIndentedString(hostCountry)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lastModified: ").append(toIndentedString(lastModified)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    officialGameNumber: ").append(toIndentedString(officialGameNumber)).append("\n");
    sb.append("    sequenceNumber: ").append(toIndentedString(sequenceNumber)).append("\n");
    sb.append("    stadium: ").append(toIndentedString(stadium)).append("\n");
    sb.append("    stadiumId: ").append(toIndentedString(stadiumId)).append("\n");
    sb.append("    startDateAndTime: ").append(toIndentedString(startDateAndTime)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

