/**
 * datalake-cache.appspot.com
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package be.ing.api.chatbot.service.model.datalake;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.LocalDateTime;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * CleanPlayerSelection
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-24T11:09:35.462+02:00")
public class CleanPlayerSelection   {
  @SerializedName("active")
  private Boolean active = null;

  @SerializedName("creationDate")
  private LocalDateTime creationDate = null;

  @SerializedName("deltaId")
  private String deltaId = null;

  @SerializedName("deltaObjectId")
  private String deltaObjectId = null;

  @SerializedName("deltaOperation")
  private Operation deltaOperation = null;

  @SerializedName("deltaTimestamp")
  private Long deltaTimestamp = null;

  @SerializedName("deltaTimestampDS")
  private Long deltaTimestampDS = null;

  @SerializedName("deltaType")
  private KbvbEntityType deltaType = null;

  @SerializedName("empty")
  private Boolean empty = null;

  @SerializedName("entityId")
  private String entityId = null;

  @SerializedName("extraUnknownFields")
  private List<UnknownObject> extraUnknownFields = new ArrayList<UnknownObject>();

  @SerializedName("hasNoId")
  private Boolean hasNoId = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("lastModified")
  private LocalDateTime lastModified = null;

  @SerializedName("links")
  private List<Link> links = new ArrayList<Link>();

  @SerializedName("matchId")
  private String matchId = null;

  @SerializedName("memberId")
  private String memberId = null;

  @SerializedName("minuteIn")
  private Integer minuteIn = null;

  @SerializedName("minuteOut")
  private Integer minuteOut = null;

  @SerializedName("minuteRed")
  private Integer minuteRed = null;

  @SerializedName("minuteYellow")
  private Integer minuteYellow = null;

  @SerializedName("minuteYellowRed")
  private String minuteYellowRed = null;

  @SerializedName("optCaptain")
  private Boolean optCaptain = null;

  @SerializedName("optKeeper")
  private Boolean optKeeper = null;

  @SerializedName("optStarter")
  private Boolean optStarter = null;

  @SerializedName("optSubstitute")
  private Boolean optSubstitute = null;

  @SerializedName("shirtNumber")
  private String shirtNumber = null;

  @SerializedName("teamId")
  private String teamId = null;

  public CleanPlayerSelection active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public CleanPlayerSelection creationDate(LocalDateTime creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
   * Get creationDate
   * @return creationDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public LocalDateTime getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(LocalDateTime creationDate) {
    this.creationDate = creationDate;
  }

  public CleanPlayerSelection deltaId(String deltaId) {
    this.deltaId = deltaId;
    return this;
  }

   /**
   * Get deltaId
   * @return deltaId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDeltaId() {
    return deltaId;
  }

  public void setDeltaId(String deltaId) {
    this.deltaId = deltaId;
  }

  public CleanPlayerSelection deltaObjectId(String deltaObjectId) {
    this.deltaObjectId = deltaObjectId;
    return this;
  }

   /**
   * Get deltaObjectId
   * @return deltaObjectId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDeltaObjectId() {
    return deltaObjectId;
  }

  public void setDeltaObjectId(String deltaObjectId) {
    this.deltaObjectId = deltaObjectId;
  }

  public CleanPlayerSelection deltaOperation(Operation deltaOperation) {
    this.deltaOperation = deltaOperation;
    return this;
  }

   /**
   * Get deltaOperation
   * @return deltaOperation
  **/
  @ApiModelProperty(example = "null", value = "")
  public Operation getDeltaOperation() {
    return deltaOperation;
  }

  public void setDeltaOperation(Operation deltaOperation) {
    this.deltaOperation = deltaOperation;
  }

  public CleanPlayerSelection deltaTimestamp(Long deltaTimestamp) {
    this.deltaTimestamp = deltaTimestamp;
    return this;
  }

   /**
   * Get deltaTimestamp
   * @return deltaTimestamp
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getDeltaTimestamp() {
    return deltaTimestamp;
  }

  public void setDeltaTimestamp(Long deltaTimestamp) {
    this.deltaTimestamp = deltaTimestamp;
  }

  public CleanPlayerSelection deltaTimestampDS(Long deltaTimestampDS) {
    this.deltaTimestampDS = deltaTimestampDS;
    return this;
  }

   /**
   * Get deltaTimestampDS
   * @return deltaTimestampDS
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getDeltaTimestampDS() {
    return deltaTimestampDS;
  }

  public void setDeltaTimestampDS(Long deltaTimestampDS) {
    this.deltaTimestampDS = deltaTimestampDS;
  }

  public CleanPlayerSelection deltaType(KbvbEntityType deltaType) {
    this.deltaType = deltaType;
    return this;
  }

   /**
   * Get deltaType
   * @return deltaType
  **/
  @ApiModelProperty(example = "null", value = "")
  public KbvbEntityType getDeltaType() {
    return deltaType;
  }

  public void setDeltaType(KbvbEntityType deltaType) {
    this.deltaType = deltaType;
  }

  public CleanPlayerSelection empty(Boolean empty) {
    this.empty = empty;
    return this;
  }

   /**
   * Get empty
   * @return empty
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getEmpty() {
    return empty;
  }

  public void setEmpty(Boolean empty) {
    this.empty = empty;
  }

  public CleanPlayerSelection entityId(String entityId) {
    this.entityId = entityId;
    return this;
  }

   /**
   * Get entityId
   * @return entityId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEntityId() {
    return entityId;
  }

  public void setEntityId(String entityId) {
    this.entityId = entityId;
  }

  public CleanPlayerSelection extraUnknownFields(List<UnknownObject> extraUnknownFields) {
    this.extraUnknownFields = extraUnknownFields;
    return this;
  }

  public CleanPlayerSelection addExtraUnknownFieldsItem(UnknownObject extraUnknownFieldsItem) {
    this.extraUnknownFields.add(extraUnknownFieldsItem);
    return this;
  }

   /**
   * Get extraUnknownFields
   * @return extraUnknownFields
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<UnknownObject> getExtraUnknownFields() {
    return extraUnknownFields;
  }

  public void setExtraUnknownFields(List<UnknownObject> extraUnknownFields) {
    this.extraUnknownFields = extraUnknownFields;
  }

  public CleanPlayerSelection hasNoId(Boolean hasNoId) {
    this.hasNoId = hasNoId;
    return this;
  }

   /**
   * Get hasNoId
   * @return hasNoId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getHasNoId() {
    return hasNoId;
  }

  public void setHasNoId(Boolean hasNoId) {
    this.hasNoId = hasNoId;
  }

  public CleanPlayerSelection id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public CleanPlayerSelection lastModified(LocalDateTime lastModified) {
    this.lastModified = lastModified;
    return this;
  }

   /**
   * Get lastModified
   * @return lastModified
  **/
  @ApiModelProperty(example = "null", value = "")
  public LocalDateTime getLastModified() {
    return lastModified;
  }

  public void setLastModified(LocalDateTime lastModified) {
    this.lastModified = lastModified;
  }

  public CleanPlayerSelection links(List<Link> links) {
    this.links = links;
    return this;
  }

  public CleanPlayerSelection addLinksItem(Link linksItem) {
    this.links.add(linksItem);
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Link> getLinks() {
    return links;
  }

  public void setLinks(List<Link> links) {
    this.links = links;
  }

  public CleanPlayerSelection matchId(String matchId) {
    this.matchId = matchId;
    return this;
  }

   /**
   * Get matchId
   * @return matchId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMatchId() {
    return matchId;
  }

  public void setMatchId(String matchId) {
    this.matchId = matchId;
  }

  public CleanPlayerSelection memberId(String memberId) {
    this.memberId = memberId;
    return this;
  }

   /**
   * Get memberId
   * @return memberId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMemberId() {
    return memberId;
  }

  public void setMemberId(String memberId) {
    this.memberId = memberId;
  }

  public CleanPlayerSelection minuteIn(Integer minuteIn) {
    this.minuteIn = minuteIn;
    return this;
  }

   /**
   * Get minuteIn
   * @return minuteIn
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getMinuteIn() {
    return minuteIn;
  }

  public void setMinuteIn(Integer minuteIn) {
    this.minuteIn = minuteIn;
  }

  public CleanPlayerSelection minuteOut(Integer minuteOut) {
    this.minuteOut = minuteOut;
    return this;
  }

   /**
   * Get minuteOut
   * @return minuteOut
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getMinuteOut() {
    return minuteOut;
  }

  public void setMinuteOut(Integer minuteOut) {
    this.minuteOut = minuteOut;
  }

  public CleanPlayerSelection minuteRed(Integer minuteRed) {
    this.minuteRed = minuteRed;
    return this;
  }

   /**
   * Get minuteRed
   * @return minuteRed
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getMinuteRed() {
    return minuteRed;
  }

  public void setMinuteRed(Integer minuteRed) {
    this.minuteRed = minuteRed;
  }

  public CleanPlayerSelection minuteYellow(Integer minuteYellow) {
    this.minuteYellow = minuteYellow;
    return this;
  }

   /**
   * Get minuteYellow
   * @return minuteYellow
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getMinuteYellow() {
    return minuteYellow;
  }

  public void setMinuteYellow(Integer minuteYellow) {
    this.minuteYellow = minuteYellow;
  }

  public CleanPlayerSelection minuteYellowRed(String minuteYellowRed) {
    this.minuteYellowRed = minuteYellowRed;
    return this;
  }

   /**
   * Get minuteYellowRed
   * @return minuteYellowRed
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMinuteYellowRed() {
    return minuteYellowRed;
  }

  public void setMinuteYellowRed(String minuteYellowRed) {
    this.minuteYellowRed = minuteYellowRed;
  }

  public CleanPlayerSelection optCaptain(Boolean optCaptain) {
    this.optCaptain = optCaptain;
    return this;
  }

   /**
   * Get optCaptain
   * @return optCaptain
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getOptCaptain() {
    return optCaptain;
  }

  public void setOptCaptain(Boolean optCaptain) {
    this.optCaptain = optCaptain;
  }

  public CleanPlayerSelection optKeeper(Boolean optKeeper) {
    this.optKeeper = optKeeper;
    return this;
  }

   /**
   * Get optKeeper
   * @return optKeeper
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getOptKeeper() {
    return optKeeper;
  }

  public void setOptKeeper(Boolean optKeeper) {
    this.optKeeper = optKeeper;
  }

  public CleanPlayerSelection optStarter(Boolean optStarter) {
    this.optStarter = optStarter;
    return this;
  }

   /**
   * Get optStarter
   * @return optStarter
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getOptStarter() {
    return optStarter;
  }

  public void setOptStarter(Boolean optStarter) {
    this.optStarter = optStarter;
  }

  public CleanPlayerSelection optSubstitute(Boolean optSubstitute) {
    this.optSubstitute = optSubstitute;
    return this;
  }

   /**
   * Get optSubstitute
   * @return optSubstitute
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getOptSubstitute() {
    return optSubstitute;
  }

  public void setOptSubstitute(Boolean optSubstitute) {
    this.optSubstitute = optSubstitute;
  }

  public CleanPlayerSelection shirtNumber(String shirtNumber) {
    this.shirtNumber = shirtNumber;
    return this;
  }

   /**
   * Get shirtNumber
   * @return shirtNumber
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getShirtNumber() {
    return shirtNumber;
  }

  public void setShirtNumber(String shirtNumber) {
    this.shirtNumber = shirtNumber;
  }

  public CleanPlayerSelection teamId(String teamId) {
    this.teamId = teamId;
    return this;
  }

   /**
   * Get teamId
   * @return teamId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTeamId() {
    return teamId;
  }

  public void setTeamId(String teamId) {
    this.teamId = teamId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CleanPlayerSelection cleanPlayerSelection = (CleanPlayerSelection) o;
    return Objects.equals(this.active, cleanPlayerSelection.active) &&
        Objects.equals(this.creationDate, cleanPlayerSelection.creationDate) &&
        Objects.equals(this.deltaId, cleanPlayerSelection.deltaId) &&
        Objects.equals(this.deltaObjectId, cleanPlayerSelection.deltaObjectId) &&
        Objects.equals(this.deltaOperation, cleanPlayerSelection.deltaOperation) &&
        Objects.equals(this.deltaTimestamp, cleanPlayerSelection.deltaTimestamp) &&
        Objects.equals(this.deltaTimestampDS, cleanPlayerSelection.deltaTimestampDS) &&
        Objects.equals(this.deltaType, cleanPlayerSelection.deltaType) &&
        Objects.equals(this.empty, cleanPlayerSelection.empty) &&
        Objects.equals(this.entityId, cleanPlayerSelection.entityId) &&
        Objects.equals(this.extraUnknownFields, cleanPlayerSelection.extraUnknownFields) &&
        Objects.equals(this.hasNoId, cleanPlayerSelection.hasNoId) &&
        Objects.equals(this.id, cleanPlayerSelection.id) &&
        Objects.equals(this.lastModified, cleanPlayerSelection.lastModified) &&
        Objects.equals(this.links, cleanPlayerSelection.links) &&
        Objects.equals(this.matchId, cleanPlayerSelection.matchId) &&
        Objects.equals(this.memberId, cleanPlayerSelection.memberId) &&
        Objects.equals(this.minuteIn, cleanPlayerSelection.minuteIn) &&
        Objects.equals(this.minuteOut, cleanPlayerSelection.minuteOut) &&
        Objects.equals(this.minuteRed, cleanPlayerSelection.minuteRed) &&
        Objects.equals(this.minuteYellow, cleanPlayerSelection.minuteYellow) &&
        Objects.equals(this.minuteYellowRed, cleanPlayerSelection.minuteYellowRed) &&
        Objects.equals(this.optCaptain, cleanPlayerSelection.optCaptain) &&
        Objects.equals(this.optKeeper, cleanPlayerSelection.optKeeper) &&
        Objects.equals(this.optStarter, cleanPlayerSelection.optStarter) &&
        Objects.equals(this.optSubstitute, cleanPlayerSelection.optSubstitute) &&
        Objects.equals(this.shirtNumber, cleanPlayerSelection.shirtNumber) &&
        Objects.equals(this.teamId, cleanPlayerSelection.teamId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(active, creationDate, deltaId, deltaObjectId, deltaOperation, deltaTimestamp, deltaTimestampDS, deltaType, empty, entityId, extraUnknownFields, hasNoId, id, lastModified, links, matchId, memberId, minuteIn, minuteOut, minuteRed, minuteYellow, minuteYellowRed, optCaptain, optKeeper, optStarter, optSubstitute, shirtNumber, teamId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CleanPlayerSelection {\n");
    
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    deltaId: ").append(toIndentedString(deltaId)).append("\n");
    sb.append("    deltaObjectId: ").append(toIndentedString(deltaObjectId)).append("\n");
    sb.append("    deltaOperation: ").append(toIndentedString(deltaOperation)).append("\n");
    sb.append("    deltaTimestamp: ").append(toIndentedString(deltaTimestamp)).append("\n");
    sb.append("    deltaTimestampDS: ").append(toIndentedString(deltaTimestampDS)).append("\n");
    sb.append("    deltaType: ").append(toIndentedString(deltaType)).append("\n");
    sb.append("    empty: ").append(toIndentedString(empty)).append("\n");
    sb.append("    entityId: ").append(toIndentedString(entityId)).append("\n");
    sb.append("    extraUnknownFields: ").append(toIndentedString(extraUnknownFields)).append("\n");
    sb.append("    hasNoId: ").append(toIndentedString(hasNoId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lastModified: ").append(toIndentedString(lastModified)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    matchId: ").append(toIndentedString(matchId)).append("\n");
    sb.append("    memberId: ").append(toIndentedString(memberId)).append("\n");
    sb.append("    minuteIn: ").append(toIndentedString(minuteIn)).append("\n");
    sb.append("    minuteOut: ").append(toIndentedString(minuteOut)).append("\n");
    sb.append("    minuteRed: ").append(toIndentedString(minuteRed)).append("\n");
    sb.append("    minuteYellow: ").append(toIndentedString(minuteYellow)).append("\n");
    sb.append("    minuteYellowRed: ").append(toIndentedString(minuteYellowRed)).append("\n");
    sb.append("    optCaptain: ").append(toIndentedString(optCaptain)).append("\n");
    sb.append("    optKeeper: ").append(toIndentedString(optKeeper)).append("\n");
    sb.append("    optStarter: ").append(toIndentedString(optStarter)).append("\n");
    sb.append("    optSubstitute: ").append(toIndentedString(optSubstitute)).append("\n");
    sb.append("    shirtNumber: ").append(toIndentedString(shirtNumber)).append("\n");
    sb.append("    teamId: ").append(toIndentedString(teamId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

