/**
 * datalake-cache.appspot.com
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package be.ing.api.chatbot.service.model.datalake;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;


/**
 * CleanDLKCampaignsPackagesCampaignPackage
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-24T11:09:35.462+02:00")
public class CleanDLKCampaignsPackagesCampaignPackage   {
  @SerializedName("campaignId")
  private String campaignId = null;

  @SerializedName("cdeVat")
  private Long cdeVat = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("invoicePrice")
  private Long invoicePrice = null;

  @SerializedName("maxAge")
  private Long maxAge = null;

  @SerializedName("minAge")
  private Long minAge = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("price")
  private Long price = null;

  @SerializedName("status")
  private String status = null;

  public CleanDLKCampaignsPackagesCampaignPackage campaignId(String campaignId) {
    this.campaignId = campaignId;
    return this;
  }

   /**
   * Get campaignId
   * @return campaignId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCampaignId() {
    return campaignId;
  }

  public void setCampaignId(String campaignId) {
    this.campaignId = campaignId;
  }

  public CleanDLKCampaignsPackagesCampaignPackage cdeVat(Long cdeVat) {
    this.cdeVat = cdeVat;
    return this;
  }

   /**
   * Get cdeVat
   * @return cdeVat
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getCdeVat() {
    return cdeVat;
  }

  public void setCdeVat(Long cdeVat) {
    this.cdeVat = cdeVat;
  }

  public CleanDLKCampaignsPackagesCampaignPackage id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public CleanDLKCampaignsPackagesCampaignPackage invoicePrice(Long invoicePrice) {
    this.invoicePrice = invoicePrice;
    return this;
  }

   /**
   * Get invoicePrice
   * @return invoicePrice
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getInvoicePrice() {
    return invoicePrice;
  }

  public void setInvoicePrice(Long invoicePrice) {
    this.invoicePrice = invoicePrice;
  }

  public CleanDLKCampaignsPackagesCampaignPackage maxAge(Long maxAge) {
    this.maxAge = maxAge;
    return this;
  }

   /**
   * Get maxAge
   * @return maxAge
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getMaxAge() {
    return maxAge;
  }

  public void setMaxAge(Long maxAge) {
    this.maxAge = maxAge;
  }

  public CleanDLKCampaignsPackagesCampaignPackage minAge(Long minAge) {
    this.minAge = minAge;
    return this;
  }

   /**
   * Get minAge
   * @return minAge
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getMinAge() {
    return minAge;
  }

  public void setMinAge(Long minAge) {
    this.minAge = minAge;
  }

  public CleanDLKCampaignsPackagesCampaignPackage name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CleanDLKCampaignsPackagesCampaignPackage price(Long price) {
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getPrice() {
    return price;
  }

  public void setPrice(Long price) {
    this.price = price;
  }

  public CleanDLKCampaignsPackagesCampaignPackage status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CleanDLKCampaignsPackagesCampaignPackage cleanDLKCampaignsPackagesCampaignPackage = (CleanDLKCampaignsPackagesCampaignPackage) o;
    return Objects.equals(this.campaignId, cleanDLKCampaignsPackagesCampaignPackage.campaignId) &&
        Objects.equals(this.cdeVat, cleanDLKCampaignsPackagesCampaignPackage.cdeVat) &&
        Objects.equals(this.id, cleanDLKCampaignsPackagesCampaignPackage.id) &&
        Objects.equals(this.invoicePrice, cleanDLKCampaignsPackagesCampaignPackage.invoicePrice) &&
        Objects.equals(this.maxAge, cleanDLKCampaignsPackagesCampaignPackage.maxAge) &&
        Objects.equals(this.minAge, cleanDLKCampaignsPackagesCampaignPackage.minAge) &&
        Objects.equals(this.name, cleanDLKCampaignsPackagesCampaignPackage.name) &&
        Objects.equals(this.price, cleanDLKCampaignsPackagesCampaignPackage.price) &&
        Objects.equals(this.status, cleanDLKCampaignsPackagesCampaignPackage.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(campaignId, cdeVat, id, invoicePrice, maxAge, minAge, name, price, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CleanDLKCampaignsPackagesCampaignPackage {\n");
    
    sb.append("    campaignId: ").append(toIndentedString(campaignId)).append("\n");
    sb.append("    cdeVat: ").append(toIndentedString(cdeVat)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    invoicePrice: ").append(toIndentedString(invoicePrice)).append("\n");
    sb.append("    maxAge: ").append(toIndentedString(maxAge)).append("\n");
    sb.append("    minAge: ").append(toIndentedString(minAge)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

