/**
 * datalake-cache.appspot.com
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package be.ing.api.chatbot.service.model.datalake;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;


/**
 * CommunityData
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-24T11:09:35.462+02:00")
public class CommunityData   {
  @SerializedName("bbfPoints")
  private Integer bbfPoints = null;

  @SerializedName("bbfScore")
  private Integer bbfScore = null;

  @SerializedName("goalsScoredAwayTeam")
  private Integer goalsScoredAwayTeam = null;

  @SerializedName("goalsScoredHomeTeam")
  private Integer goalsScoredHomeTeam = null;

  @SerializedName("penaltyShootOutsScoredAwayTeam")
  private Integer penaltyShootOutsScoredAwayTeam = null;

  @SerializedName("penaltyShootOutsScoredHomeTeam")
  private Integer penaltyShootOutsScoredHomeTeam = null;

  @SerializedName("scoreAccuracy")
  private Integer scoreAccuracy = null;

  public CommunityData bbfPoints(Integer bbfPoints) {
    this.bbfPoints = bbfPoints;
    return this;
  }

   /**
   * Get bbfPoints
   * @return bbfPoints
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getBbfPoints() {
    return bbfPoints;
  }

  public void setBbfPoints(Integer bbfPoints) {
    this.bbfPoints = bbfPoints;
  }

  public CommunityData bbfScore(Integer bbfScore) {
    this.bbfScore = bbfScore;
    return this;
  }

   /**
   * Get bbfScore
   * @return bbfScore
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getBbfScore() {
    return bbfScore;
  }

  public void setBbfScore(Integer bbfScore) {
    this.bbfScore = bbfScore;
  }

  public CommunityData goalsScoredAwayTeam(Integer goalsScoredAwayTeam) {
    this.goalsScoredAwayTeam = goalsScoredAwayTeam;
    return this;
  }

   /**
   * Get goalsScoredAwayTeam
   * @return goalsScoredAwayTeam
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getGoalsScoredAwayTeam() {
    return goalsScoredAwayTeam;
  }

  public void setGoalsScoredAwayTeam(Integer goalsScoredAwayTeam) {
    this.goalsScoredAwayTeam = goalsScoredAwayTeam;
  }

  public CommunityData goalsScoredHomeTeam(Integer goalsScoredHomeTeam) {
    this.goalsScoredHomeTeam = goalsScoredHomeTeam;
    return this;
  }

   /**
   * Get goalsScoredHomeTeam
   * @return goalsScoredHomeTeam
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getGoalsScoredHomeTeam() {
    return goalsScoredHomeTeam;
  }

  public void setGoalsScoredHomeTeam(Integer goalsScoredHomeTeam) {
    this.goalsScoredHomeTeam = goalsScoredHomeTeam;
  }

  public CommunityData penaltyShootOutsScoredAwayTeam(Integer penaltyShootOutsScoredAwayTeam) {
    this.penaltyShootOutsScoredAwayTeam = penaltyShootOutsScoredAwayTeam;
    return this;
  }

   /**
   * Get penaltyShootOutsScoredAwayTeam
   * @return penaltyShootOutsScoredAwayTeam
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getPenaltyShootOutsScoredAwayTeam() {
    return penaltyShootOutsScoredAwayTeam;
  }

  public void setPenaltyShootOutsScoredAwayTeam(Integer penaltyShootOutsScoredAwayTeam) {
    this.penaltyShootOutsScoredAwayTeam = penaltyShootOutsScoredAwayTeam;
  }

  public CommunityData penaltyShootOutsScoredHomeTeam(Integer penaltyShootOutsScoredHomeTeam) {
    this.penaltyShootOutsScoredHomeTeam = penaltyShootOutsScoredHomeTeam;
    return this;
  }

   /**
   * Get penaltyShootOutsScoredHomeTeam
   * @return penaltyShootOutsScoredHomeTeam
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getPenaltyShootOutsScoredHomeTeam() {
    return penaltyShootOutsScoredHomeTeam;
  }

  public void setPenaltyShootOutsScoredHomeTeam(Integer penaltyShootOutsScoredHomeTeam) {
    this.penaltyShootOutsScoredHomeTeam = penaltyShootOutsScoredHomeTeam;
  }

  public CommunityData scoreAccuracy(Integer scoreAccuracy) {
    this.scoreAccuracy = scoreAccuracy;
    return this;
  }

   /**
   * Get scoreAccuracy
   * @return scoreAccuracy
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getScoreAccuracy() {
    return scoreAccuracy;
  }

  public void setScoreAccuracy(Integer scoreAccuracy) {
    this.scoreAccuracy = scoreAccuracy;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommunityData communityData = (CommunityData) o;
    return Objects.equals(this.bbfPoints, communityData.bbfPoints) &&
        Objects.equals(this.bbfScore, communityData.bbfScore) &&
        Objects.equals(this.goalsScoredAwayTeam, communityData.goalsScoredAwayTeam) &&
        Objects.equals(this.goalsScoredHomeTeam, communityData.goalsScoredHomeTeam) &&
        Objects.equals(this.penaltyShootOutsScoredAwayTeam, communityData.penaltyShootOutsScoredAwayTeam) &&
        Objects.equals(this.penaltyShootOutsScoredHomeTeam, communityData.penaltyShootOutsScoredHomeTeam) &&
        Objects.equals(this.scoreAccuracy, communityData.scoreAccuracy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bbfPoints, bbfScore, goalsScoredAwayTeam, goalsScoredHomeTeam, penaltyShootOutsScoredAwayTeam, penaltyShootOutsScoredHomeTeam, scoreAccuracy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommunityData {\n");
    
    sb.append("    bbfPoints: ").append(toIndentedString(bbfPoints)).append("\n");
    sb.append("    bbfScore: ").append(toIndentedString(bbfScore)).append("\n");
    sb.append("    goalsScoredAwayTeam: ").append(toIndentedString(goalsScoredAwayTeam)).append("\n");
    sb.append("    goalsScoredHomeTeam: ").append(toIndentedString(goalsScoredHomeTeam)).append("\n");
    sb.append("    penaltyShootOutsScoredAwayTeam: ").append(toIndentedString(penaltyShootOutsScoredAwayTeam)).append("\n");
    sb.append("    penaltyShootOutsScoredHomeTeam: ").append(toIndentedString(penaltyShootOutsScoredHomeTeam)).append("\n");
    sb.append("    scoreAccuracy: ").append(toIndentedString(scoreAccuracy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

