/**
 * datalake-cache.appspot.com
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package be.ing.api.chatbot.service.model.datalake;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;


/**
 * Committee
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-24T11:09:35.462+02:00")
public class Committee   {
  @SerializedName("blockNumber")
  private Integer blockNumber = null;

  @SerializedName("committee")
  private String committee = null;

  @SerializedName("discipline")
  private String discipline = null;

  @SerializedName("fired")
  private Boolean fired = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("refereeObserverNumber")
  private String refereeObserverNumber = null;

  @SerializedName("startDate")
  private String startDate = null;

  public Committee blockNumber(Integer blockNumber) {
    this.blockNumber = blockNumber;
    return this;
  }

   /**
   * Get blockNumber
   * @return blockNumber
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getBlockNumber() {
    return blockNumber;
  }

  public void setBlockNumber(Integer blockNumber) {
    this.blockNumber = blockNumber;
  }

  public Committee committee(String committee) {
    this.committee = committee;
    return this;
  }

   /**
   * Get committee
   * @return committee
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCommittee() {
    return committee;
  }

  public void setCommittee(String committee) {
    this.committee = committee;
  }

  public Committee discipline(String discipline) {
    this.discipline = discipline;
    return this;
  }

   /**
   * Get discipline
   * @return discipline
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDiscipline() {
    return discipline;
  }

  public void setDiscipline(String discipline) {
    this.discipline = discipline;
  }

  public Committee fired(Boolean fired) {
    this.fired = fired;
    return this;
  }

   /**
   * Get fired
   * @return fired
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getFired() {
    return fired;
  }

  public void setFired(Boolean fired) {
    this.fired = fired;
  }

  public Committee id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Committee refereeObserverNumber(String refereeObserverNumber) {
    this.refereeObserverNumber = refereeObserverNumber;
    return this;
  }

   /**
   * Get refereeObserverNumber
   * @return refereeObserverNumber
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRefereeObserverNumber() {
    return refereeObserverNumber;
  }

  public void setRefereeObserverNumber(String refereeObserverNumber) {
    this.refereeObserverNumber = refereeObserverNumber;
  }

  public Committee startDate(String startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStartDate() {
    return startDate;
  }

  public void setStartDate(String startDate) {
    this.startDate = startDate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Committee committee = (Committee) o;
    return Objects.equals(this.blockNumber, committee.blockNumber) &&
        Objects.equals(this.committee, committee.committee) &&
        Objects.equals(this.discipline, committee.discipline) &&
        Objects.equals(this.fired, committee.fired) &&
        Objects.equals(this.id, committee.id) &&
        Objects.equals(this.refereeObserverNumber, committee.refereeObserverNumber) &&
        Objects.equals(this.startDate, committee.startDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(blockNumber, committee, discipline, fired, id, refereeObserverNumber, startDate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Committee {\n");
    
    sb.append("    blockNumber: ").append(toIndentedString(blockNumber)).append("\n");
    sb.append("    committee: ").append(toIndentedString(committee)).append("\n");
    sb.append("    discipline: ").append(toIndentedString(discipline)).append("\n");
    sb.append("    fired: ").append(toIndentedString(fired)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    refereeObserverNumber: ").append(toIndentedString(refereeObserverNumber)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

