/**
 * datalake-cache.appspot.com
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package be.ing.api.chatbot.service.model.datalake;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * Mission
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-24T11:09:35.462+02:00")
public class Mission   {
  @SerializedName("id")
  private String id = null;

  @SerializedName("links")
  private List<Link> links = new ArrayList<Link>();

  @SerializedName("missionDateAndTime")
  private String missionDateAndTime = null;

  @SerializedName("refereeFirstName")
  private String refereeFirstName = null;

  @SerializedName("refereeLastName")
  private String refereeLastName = null;

  @SerializedName("refereeObserverFirstName")
  private String refereeObserverFirstName = null;

  @SerializedName("refereeObserverLastName")
  private String refereeObserverLastName = null;

  public Mission id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Mission links(List<Link> links) {
    this.links = links;
    return this;
  }

  public Mission addLinksItem(Link linksItem) {
    this.links.add(linksItem);
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Link> getLinks() {
    return links;
  }

  public void setLinks(List<Link> links) {
    this.links = links;
  }

  public Mission missionDateAndTime(String missionDateAndTime) {
    this.missionDateAndTime = missionDateAndTime;
    return this;
  }

   /**
   * Get missionDateAndTime
   * @return missionDateAndTime
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMissionDateAndTime() {
    return missionDateAndTime;
  }

  public void setMissionDateAndTime(String missionDateAndTime) {
    this.missionDateAndTime = missionDateAndTime;
  }

  public Mission refereeFirstName(String refereeFirstName) {
    this.refereeFirstName = refereeFirstName;
    return this;
  }

   /**
   * Get refereeFirstName
   * @return refereeFirstName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRefereeFirstName() {
    return refereeFirstName;
  }

  public void setRefereeFirstName(String refereeFirstName) {
    this.refereeFirstName = refereeFirstName;
  }

  public Mission refereeLastName(String refereeLastName) {
    this.refereeLastName = refereeLastName;
    return this;
  }

   /**
   * Get refereeLastName
   * @return refereeLastName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRefereeLastName() {
    return refereeLastName;
  }

  public void setRefereeLastName(String refereeLastName) {
    this.refereeLastName = refereeLastName;
  }

  public Mission refereeObserverFirstName(String refereeObserverFirstName) {
    this.refereeObserverFirstName = refereeObserverFirstName;
    return this;
  }

   /**
   * Get refereeObserverFirstName
   * @return refereeObserverFirstName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRefereeObserverFirstName() {
    return refereeObserverFirstName;
  }

  public void setRefereeObserverFirstName(String refereeObserverFirstName) {
    this.refereeObserverFirstName = refereeObserverFirstName;
  }

  public Mission refereeObserverLastName(String refereeObserverLastName) {
    this.refereeObserverLastName = refereeObserverLastName;
    return this;
  }

   /**
   * Get refereeObserverLastName
   * @return refereeObserverLastName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRefereeObserverLastName() {
    return refereeObserverLastName;
  }

  public void setRefereeObserverLastName(String refereeObserverLastName) {
    this.refereeObserverLastName = refereeObserverLastName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Mission mission = (Mission) o;
    return Objects.equals(this.id, mission.id) &&
        Objects.equals(this.links, mission.links) &&
        Objects.equals(this.missionDateAndTime, mission.missionDateAndTime) &&
        Objects.equals(this.refereeFirstName, mission.refereeFirstName) &&
        Objects.equals(this.refereeLastName, mission.refereeLastName) &&
        Objects.equals(this.refereeObserverFirstName, mission.refereeObserverFirstName) &&
        Objects.equals(this.refereeObserverLastName, mission.refereeObserverLastName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, links, missionDateAndTime, refereeFirstName, refereeLastName, refereeObserverFirstName, refereeObserverLastName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Mission {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    missionDateAndTime: ").append(toIndentedString(missionDateAndTime)).append("\n");
    sb.append("    refereeFirstName: ").append(toIndentedString(refereeFirstName)).append("\n");
    sb.append("    refereeLastName: ").append(toIndentedString(refereeLastName)).append("\n");
    sb.append("    refereeObserverFirstName: ").append(toIndentedString(refereeObserverFirstName)).append("\n");
    sb.append("    refereeObserverLastName: ").append(toIndentedString(refereeObserverLastName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

