/**
 * datalake-cache.appspot.com
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package be.ing.api.chatbot.service.model.datalake;

import com.google.gson.annotations.SerializedName;



/**
 * Gets or Sets Month
 */
public enum Month {
  
  @SerializedName("JANUARY")
  JANUARY("JANUARY"),
  
  @SerializedName("FEBRUARY")
  FEBRUARY("FEBRUARY"),
  
  @SerializedName("MARCH")
  MARCH("MARCH"),
  
  @SerializedName("APRIL")
  APRIL("APRIL"),
  
  @SerializedName("MAY")
  MAY("MAY"),
  
  @SerializedName("JUNE")
  JUNE("JUNE"),
  
  @SerializedName("JULY")
  JULY("JULY"),
  
  @SerializedName("AUGUST")
  AUGUST("AUGUST"),
  
  @SerializedName("SEPTEMBER")
  SEPTEMBER("SEPTEMBER"),
  
  @SerializedName("OCTOBER")
  OCTOBER("OCTOBER"),
  
  @SerializedName("NOVEMBER")
  NOVEMBER("NOVEMBER"),
  
  @SerializedName("DECEMBER")
  DECEMBER("DECEMBER");

  private String value;

  Month(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }
}

