/**
 * datalake-cache.appspot.com
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package be.ing.api.chatbot.service.model.datalake;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;


/**
 * Timeslot
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-24T11:09:35.462+02:00")
public class Timeslot   {
  @SerializedName("committee")
  private String committee = null;

  @SerializedName("discipline")
  private String discipline = null;

  @SerializedName("endDateAndTime")
  private String endDateAndTime = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("startDateAndTime")
  private String startDateAndTime = null;

  @SerializedName("type")
  private String type = null;

  public Timeslot committee(String committee) {
    this.committee = committee;
    return this;
  }

   /**
   * Get committee
   * @return committee
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCommittee() {
    return committee;
  }

  public void setCommittee(String committee) {
    this.committee = committee;
  }

  public Timeslot discipline(String discipline) {
    this.discipline = discipline;
    return this;
  }

   /**
   * Get discipline
   * @return discipline
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDiscipline() {
    return discipline;
  }

  public void setDiscipline(String discipline) {
    this.discipline = discipline;
  }

  public Timeslot endDateAndTime(String endDateAndTime) {
    this.endDateAndTime = endDateAndTime;
    return this;
  }

   /**
   * Get endDateAndTime
   * @return endDateAndTime
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEndDateAndTime() {
    return endDateAndTime;
  }

  public void setEndDateAndTime(String endDateAndTime) {
    this.endDateAndTime = endDateAndTime;
  }

  public Timeslot id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Timeslot startDateAndTime(String startDateAndTime) {
    this.startDateAndTime = startDateAndTime;
    return this;
  }

   /**
   * Get startDateAndTime
   * @return startDateAndTime
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStartDateAndTime() {
    return startDateAndTime;
  }

  public void setStartDateAndTime(String startDateAndTime) {
    this.startDateAndTime = startDateAndTime;
  }

  public Timeslot type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Timeslot timeslot = (Timeslot) o;
    return Objects.equals(this.committee, timeslot.committee) &&
        Objects.equals(this.discipline, timeslot.discipline) &&
        Objects.equals(this.endDateAndTime, timeslot.endDateAndTime) &&
        Objects.equals(this.id, timeslot.id) &&
        Objects.equals(this.startDateAndTime, timeslot.startDateAndTime) &&
        Objects.equals(this.type, timeslot.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(committee, discipline, endDateAndTime, id, startDateAndTime, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Timeslot {\n");
    
    sb.append("    committee: ").append(toIndentedString(committee)).append("\n");
    sb.append("    discipline: ").append(toIndentedString(discipline)).append("\n");
    sb.append("    endDateAndTime: ").append(toIndentedString(endDateAndTime)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    startDateAndTime: ").append(toIndentedString(startDateAndTime)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

