@startuml

skinparam roundcorner 10
skinparam maxmessagesize 180

title <b><font size="20">Sequence flow for MVP1 - Generic Flow</font></b>

actor UserOnWebsite
participant ChatBotApi
participant DialogFlowApi
participant FourCastApi

UserOnWebsite -> ChatBotApi: get(plain text, context+params, userId and sessionId)
ChatBotApi -> DialogFlowApi: get(plain text, context+params and sessionId)
DialogFlowApi -> DialogFlowApi: Isolate intent and keywords based on input
DialogFlowApi -> ChatBotApi: return intent and keywords
ChatBotApi -> ChatBotApi: prepare data and context
ChatBotApi -> FourCastApi: get(context and keywords)
FourCastApi -> FourCastApi: Extract data based on keywords for a given context
FourCastApi -> ChatBotApi: return data corresponding to keywords
ChatBotApi -> UserOnWebsite: return data, context+params and sessionId for next request

@enduml